// preact-app/src/views/TodoList.jsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { fetchTodos, addTodo, toggleTodo } from '../api'

export default function TodoList() {
  const client = useQueryClient()
  const [title, setTitle] = useState('')

  const query = useQuery({
    queryKey: ['todos'],
    queryFn: () => fetchTodos(),
  })

  const add = useMutation({
    mutationFn: (t) => addTodo(t),
    onSuccess: () => client.invalidateQueries({ queryKey: ['todos'] }),
  })

  const toggle = useMutation({
    mutationFn: (id) => toggleTodo(id),
    onMutate: async (id) => {
      await client.cancelQueries({ queryKey: ['todos'] })
      const prev = client.getQueryData(['todos'])
      client.setQueryData(['todos'], (old) =>
        old.map((t) => (t.id === id ? { ...t, done: !t.done } : t))
      )
      return { prev }
    },
    onError: (_err, _id, ctx) => {
      client.setQueryData(['todos'], ctx.prev)
    },
  })

  if (query.isLoading) return <p>Loading…</p>

  return (
    <div>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          if (!title) return
          add.mutate(title)
          setTitle('')
        }}
      >
        <input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="New todo"
        />
        <button type="submit" disabled={add.status === 'pending'}>
          Add
        </button>
      </form>

      {query.isFetching && <p>Refreshing…</p>}
      <ul>
        {query.data.map((todo) => (
          <li key={todo.id}>
            <input
              type="checkbox"
              checked={todo.done}
              onChange={() => toggle.mutate(todo.id)}
            />
            <Link to={`/todo/${todo.id}`}>{todo.title}</Link>
          </li>
        ))}
      </ul>
    </div>
  )
}

// svelte-app/src/views/TodoList.svelte
<script>
  import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query'
  import { fetchTodos, addTodo, toggleTodo } from '../api'

  const client = useQueryClient()
  let title = $state('')

  const query = createQuery(() => ({
    queryKey: ['todos'],
    queryFn: () => fetchTodos(),
  }))

  const add = createMutation(() => ({
    mutationFn: (t) => addTodo(t),
    onSuccess: () => client.invalidateQueries({ queryKey: ['todos'] }),
  }))

  const toggle = createMutation(() => ({
    mutationFn: (id) => toggleTodo(id),
    onMutate: async (id) => {
      await client.cancelQueries({ queryKey: ['todos'] })
      const prev = client.getQueryData(['todos'])
      client.setQueryData(['todos'], (old) =>
        old.map((t) => (t.id === id ? { ...t, done: !t.done } : t))
      )
      return { prev }
    },
    onError: (_err, _id, ctx) => {
      client.setQueryData(['todos'], ctx.prev)
    },
  }))

  function onAdd(e) {
    e.preventDefault()
    if (!title) return
    add.mutate(title)
    title = ''
  }
</script>

{#if query.isLoading}
  <p>Loading…</p>
{:else}
  <form onsubmit={onAdd}>
    <input bind:value={title} placeholder="New todo" />
    <button type="submit" disabled={add.status === 'pending'}>Add</button>
  </form>

  {#if query.isFetching}<p>Refreshing…</p>{/if}
  <ul>
    {#each query.data as todo (todo.id)}
      <li>
        <input
          type="checkbox"
          checked={todo.done}
          onchange={() => toggle.mutate(todo.id)}
        />
        <a href={`#/todo/${todo.id}`}>{todo.title}</a>
      </li>
    {/each}
  </ul>
{/if}
