// next-app/app/todo/[id]/todo-detail.jsx
'use client'

import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useQuery, useMutation } from '@tanstack/react-query'
import { fetchTodo, toggleTodo } from '../../../lib/api'

export default function TodoDetail() {
  const { id } = useParams()

  const query = useQuery({
    queryKey: ['todo', id],
    queryFn: () => fetchTodo(id),
  })

  const toggle = useMutation({
    mutationFn: (todoId) => toggleTodo(todoId),
    onSuccess: () => query.refetch(),
  })

  if (query.isLoading) return <p>Loading…</p>

  return (
    <div>
      <Link href="/">← Back</Link>
      <h2>{query.data.title}</h2>
      <p>Status: {query.data.done ? 'Done' : 'Open'}</p>
      <button onClick={() => toggle.mutate(query.data.id)}>Toggle</button>
    </div>
  )
}

// svelte-app/src/views/TodoDetail.svelte
<script>
  import { createQuery, createMutation } from '@tanstack/svelte-query'
  import { fetchTodo, toggleTodo } from '../api'

  let { params } = $props()

  const query = createQuery(() => ({
    queryKey: ['todo', params.id],
    queryFn: () => fetchTodo(params.id),
  }))

  const toggle = createMutation(() => ({
    mutationFn: (id) => toggleTodo(id),
    onSuccess: () => query.refetch(),
  }))
</script>

{#if query.isLoading}
  <p>Loading…</p>
{:else}
  <a href="#/">← Back</a>
  <h2>{query.data.title}</h2>
  <p>Status: {query.data.done ? 'Done' : 'Open'}</p>
  <button onclick={() => toggle.mutate(query.data.id)}>Toggle</button>
{/if}
