// nuxt-app/app/pages/todo/[id].vue
<template>
  <div>
    <NuxtLink to="/">← Back</NuxtLink>
    <h2>{{ query.data?.title }}</h2>
    <p>Status: {{ query.data?.done ? 'Done' : 'Open' }}</p>
    <button @click="toggle.mutate(query.data.id)">Toggle</button>
  </div>
</template>

<script setup>
import { useRoute } from 'vue-router'
import { useQuery, useMutation } from '@dts/vue-uquery'
import { fetchTodo, toggleTodo } from '../../lib/api'

const route = useRoute()

const query = await useQuery({
  key: ['todo', route.params.id],
  fetcher: () => fetchTodo(route.params.id),
})

const toggle = useMutation({
  mutator: (id) => toggleTodo(id),
  onSuccess: () => query.refetch(),
})
</script>

// sveltekit-app/src/routes/todo/[id]/+page.svelte
<script>
  import { createQuery, createMutation } from '@tanstack/svelte-query'
  import { page } from '$app/state'
  import { base } from '$app/paths'
  import { fetchTodo, toggleTodo } from '$lib/api'

  const id = $derived(page.params.id)

  const query = createQuery(() => ({
    queryKey: ['todo', id],
    queryFn: () => fetchTodo(id),
  }))

  const toggle = createMutation(() => ({
    mutationFn: (todoId) => toggleTodo(todoId),
    onSuccess: () => query.refetch(),
  }))
</script>

{#if query.isLoading}
  <p>Loading…</p>
{:else}
  <a href="{base}/">← Back</a>
  <h2>{query.data.title}</h2>
  <p>Status: {query.data.done ? 'Done' : 'Open'}</p>
  <button onclick={() => toggle.mutate(query.data.id)}>Toggle</button>
{/if}
