// vue-app/src/views/TodoDetail.vue
<template>
  <div>
    <RouterLink to="/">← Back</RouterLink>
    <h2>{{ query.data?.title }}</h2>
    <p>Status: {{ query.data?.done ? 'Done' : 'Open' }}</p>
    <button @click="toggle.mutate(query.data.id)">Toggle</button>
  </div>
</template>

<script setup>
import { useRoute } from 'vue-router'
import { useQuery, useMutation } from '@dts/vue-uquery'
import { fetchTodo, toggleTodo } from '../api'

const route = useRoute()

const query = await useQuery({
  key: ['todo', route.params.id],
  fetcher: () => fetchTodo(route.params.id),
})

const toggle = useMutation({
  mutator: (id) => toggleTodo(id),
  onSuccess: () => query.refetch(),
})
</script>

// preact-app/src/views/TodoDetail.jsx
import { Link, useParams } from 'react-router-dom'
import { useQuery, useMutation } from '@tanstack/react-query'
import { fetchTodo, toggleTodo } from '../api'

export default function TodoDetail() {
  const { id } = useParams()

  const query = useQuery({
    queryKey: ['todo', id],
    queryFn: () => fetchTodo(id),
  })

  const toggle = useMutation({
    mutationFn: (todoId) => toggleTodo(todoId),
    onSuccess: () => query.refetch(),
  })

  if (query.isLoading) return <p>Loading…</p>

  return (
    <div>
      <Link to="/">← Back</Link>
      <h2>{query.data.title}</h2>
      <p>Status: {query.data.done ? 'Done' : 'Open'}</p>
      <button onClick={() => toggle.mutate(query.data.id)}>Toggle</button>
    </div>
  )
}
